name: using secret keys as part of workflow

on: push

jobs:
  build:
    env: 
      SOME_JOB_ENVIROMENT_VARIABLE: "some alphanumeric"
    runs-on: ubuntu-latest
    steps:
      - name: Setup some environment variables
        run: echo "$SOME_JOB_ENVIROMENT_VARIABLE"
      - name: Log into aws
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2
